import { describe, expect, it } from 'vitest';
import type { AiTone, TrialData, UserSettings } from '@/types/api';
import type {
    EditHabit,
    HabitFormData,
    NotificationTime,
    TemplateHabit,
} from '@/types/edit';
import type { ActivityDay, Habit, TrackData } from '@/types/track';
import type {
    GridHabit,
    LifeViewData,
    WeekActivityData,
    WeekDay,
    WeekViewData,
    YearActivityData,
    YearViewData,
} from '@/types/view';
import apiSchema from '../api-schema.json';

type SchemaMap = typeof apiSchema.components.schemas;

/**
 * Returns sorted property names from an OpenAPI component schema.
 */
function schemaKeys(name: keyof SchemaMap): string[] {
    const schema = apiSchema.components.schemas[name] as {
        properties?: Record<string, unknown>;
    };

    return Object.keys(schema.properties ?? {}).sort();
}

/**
 * Builds a sorted list of keys from a TypeScript type.
 *
 * The mapped type `{ [K in keyof Required<T>]: true }` ensures every
 * property of T must be listed — a compile error fires if one is
 * missing.  Comparing this list against the OpenAPI schema catches
 * additions / removals on either side.
 */
function typeKeys<T>(obj: { [K in keyof Required<T>]: true }): string[] {
    return Object.keys(obj).sort();
}

// ─── Coverage Tracking ──────────────────────────────────────────
//
// Every schema in api-schema.json must appear in exactly one of these sets.
// If a backend resource is added, `api-schema.json` gains a new entry and the
// coverage test below will fail until the developer adds a type test and lists
// the schema in TESTED_SCHEMAS, or explicitly marks it as EXCLUDED_SCHEMAS.

/**
 * Schemas that have a corresponding TypeScript type test in this file.
 * Every entry here must have an `it('XResource schema matches ...')` below.
 */
const TESTED_SCHEMAS = new Set([
    'AiToneResource',
    'EditHabitResource',
    'HabitActivityDataResource',
    'HabitFormResource',
    'HabitNotificationResource',
    'HabitResource',
    'HabitTemplateResource',
    'LifeActivityResource',
    'LifeViewResource',
    'TrackResource',
    'TrialResource',
    'UserSettingResource',
    'WeekDayResource',
    'WeekGridHabitResource',
    'WeekViewResource',
    'YearActivityResource',
    'YearViewResource',
]);

/**
 * Schemas intentionally excluded from type matching.
 * - Request body schemas have no TypeScript response type counterpart.
 * - Schemas with no enumerable `properties` cannot be compared with typeKeys.
 */
const EXCLUDED_SCHEMAS = new Set([
    'NavigationTranslationResource', // no enumerable properties in schema
    'NoteRequest', // request body
    'ReorderHabitsRequest', // request body
    'StoreHabitRequest', // request body
    'ToggleRequest', // request body
    'UpdateSettingsRequest', // request body
]);

/**
 * All API paths we are aware of.
 * If a new endpoint is added to the backend, `api-schema.json` gains a new
 * path and the coverage test below will fail until it is listed here.
 */
const KNOWN_PATHS = new Set([
    '/track',
    '/track/toggle',
    '/track/daily-note',
    '/edit',
    '/edit/habits/create',
    '/edit/habits/{habit}',
    '/edit/habits',
    '/edit/habits/{habit}/toggle',
    '/edit/toggle-franklin',
    '/edit/habits/reorder',
    '/edit/templates/{habitTemplate}/copy',
    '/view/week',
    '/view/year',
    '/view/life',
    '/settings',
    '/settings/trial-banner/dismiss',
]);

// ─── API Contract Tests ─────────────────────────────────────────
//
// These tests verify that the frontend TypeScript types stay in sync
// with the backend API schema generated by Scramble.
//
// If a backend resource adds or removes a field, `api-schema.json`
// changes and the corresponding assertion below will fail, forcing
// the developer to update the TypeScript type (or revert the backend
// change).

describe('API contract', () => {
    it('TrackResource schema matches TrackData type', () => {
        const schema = schemaKeys('TrackResource');
        const ts = typeKeys<Omit<TrackData, 'habits' | 'activityData'>>({
            date: true,
            dayName: true,
            dateFormatted: true,
            isToday: true,
            totalHabits: true,
            completedCount: true,
            dailyNoteContent: true,
            translations: true,
        });

        expect(schema).toEqual(ts);
    });

    it('HabitResource schema matches Habit type', () => {
        const schema = schemaKeys('HabitResource');
        const ts = typeKeys<Habit>({
            id: true,
            name: true,
            description: true,
            iterations_required: true,
            is_completed: true,
            current_iteration: true,
            sort_order: true,
        });

        expect(schema).toEqual(ts);
    });

    it('HabitActivityDataResource schema matches ActivityDay type', () => {
        const schema = schemaKeys('HabitActivityDataResource');
        const ts = typeKeys<ActivityDay>({
            date: true,
            percentage: true,
            completed: true,
            total: true,
            intensity: true,
        });

        expect(schema).toEqual(ts);
    });

    it('WeekViewResource schema matches WeekViewData type', () => {
        const schema = schemaKeys('WeekViewResource');
        const ts = typeKeys<WeekViewData>({
            start: true,
            end: true,
            startFormatted: true,
            endFormatted: true,
            endFormattedFull: true,
            year: true,
            isCurrent: true,
        });

        expect(schema).toEqual(ts);
    });

    it('WeekDayResource schema matches WeekDay type', () => {
        const schema = schemaKeys('WeekDayResource');
        const ts = typeKeys<WeekDay>({
            date: true,
            day_name: true,
            day_number: true,
            is_today: true,
            is_future: true,
        });

        expect(schema).toEqual(ts);
    });

    it('WeekGridHabitResource schema matches GridHabit type', () => {
        const schema = schemaKeys('WeekGridHabitResource');
        const ts = typeKeys<GridHabit>({
            id: true,
            name: true,
            category: true,
            is_weekly_focus: true,
            is_franklin_virtue: true,
            days: true,
        });

        expect(schema).toEqual(ts);
    });

    it('YearViewResource schema matches YearViewData type', () => {
        const schema = schemaKeys('YearViewResource');
        const ts = typeKeys<YearViewData>({
            selected: true,
            birthdate: true,
            currentAge: true,
        });

        expect(schema).toEqual(ts);
    });

    it('YearActivityResource schema matches WeekActivityData type', () => {
        const schema = schemaKeys('YearActivityResource');
        const ts = typeKeys<WeekActivityData>({
            weekNum: true,
            intensity: true,
            completed: true,
            total: true,
        });

        expect(schema).toEqual(ts);
    });

    it('LifeViewResource schema matches LifeViewData type', () => {
        const schema = schemaKeys('LifeViewResource');
        const ts = typeKeys<LifeViewData>({
            birthdate: true,
            currentAge: true,
            weeksLived: true,
            yearsRemaining: true,
        });

        expect(schema).toEqual(ts);
    });

    it('LifeActivityResource schema matches YearActivityData type', () => {
        const schema = schemaKeys('LifeActivityResource');
        const ts = typeKeys<YearActivityData>({
            year: true,
            intensity: true,
            completed: true,
            total: true,
        });

        expect(schema).toEqual(ts);
    });

    it('EditHabitResource schema matches EditHabit type', () => {
        const schema = schemaKeys('EditHabitResource');
        const ts = typeKeys<EditHabit>({
            id: true,
            name: true,
            description: true,
            is_active: true,
            sort_order: true,
            iterations_required: true,
            human_readable: true,
            is_franklin_virtue: true,
        });

        expect(schema).toEqual(ts);
    });

    it('HabitFormResource schema matches HabitFormData type', () => {
        const schema = schemaKeys('HabitFormResource');
        const ts = typeKeys<Required<HabitFormData>>({
            id: true,
            name: true,
            description: true,
            iterations_required: true,
            is_active: true,
            frequency: true,
            weekly_days: true,
            monthly_days: true,
            monthly_mode: true,
            monthly_position: true,
            monthly_weekday: true,
            notifications: true,
        });

        expect(schema).toEqual(ts);
    });

    it('HabitNotificationResource schema matches NotificationTime type', () => {
        const schema = schemaKeys('HabitNotificationResource');
        const ts = typeKeys<NotificationTime>({
            time: true,
            is_active: true,
        });

        expect(schema).toEqual(ts);
    });

    it('UserSettingResource schema matches UserSettings type', () => {
        const schema = schemaKeys('UserSettingResource');
        const ts = typeKeys<UserSettings>({
            locale: true,
            theme: true,
            moveCompletedToEnd: true,
            timezone: true,
            dayStartsAt: true,
            birthdate: true,
            aiDigestTime: true,
            aiToneId: true,
            trial: true,
        });

        expect(schema).toEqual(ts);
    });

    it('TrialResource schema matches TrialData type', () => {
        const schema = schemaKeys('TrialResource');
        const ts = typeKeys<TrialData>({
            shouldShowBanner: true,
            bannerText: true,
            invoiceLink: true,
            learnMore: true,
            featuresTitle: true,
            featuresSubtitle: true,
            featureNotifications: true,
            featureAiDigest: true,
            featureExport: true,
            upgradeLabel: true,
            openInTelegramLabel: true,
        });

        expect(schema).toEqual(ts);
    });

    it('AiToneResource schema matches AiTone type', () => {
        const schema = schemaKeys('AiToneResource');
        const ts = typeKeys<AiTone>({
            id: true,
            name: true,
            description: true,
            icon: true,
        });

        expect(schema).toEqual(ts);
    });

    it('HabitTemplateResource schema matches TemplateHabit type', () => {
        const schema = schemaKeys('HabitTemplateResource');
        const ts = typeKeys<TemplateHabit>({
            id: true,
            name: true,
            human_readable: true,
            iterations_required: true,
            category: true,
            sort_order: true,
        });

        expect(schema).toEqual(ts);
    });

    it('/edit response envelope has correct keys', () => {
        const editPath = apiSchema.paths['/edit'] as {
            get: {
                responses: {
                    '200': {
                        content: {
                            'application/json': {
                                schema: {
                                    required: string[];
                                    properties: Record<string, unknown>;
                                };
                            };
                        };
                    };
                };
            };
        };
        const responseSchema =
            editPath.get.responses['200'].content['application/json'].schema;
        const keys = Object.keys(responseSchema.properties).sort();

        expect(keys).toEqual(
            [
                'data',
                'minSortOrder',
                'navigationTranslations',
                'settings',
                'templates',
                'translations',
            ].sort(),
        );
    });

    // ─── Coverage Meta-Tests ──────────────────────────────────────
    //
    // These tests ensure that every schema and path in api-schema.json is
    // accounted for. When the backend adds a new resource or endpoint, the
    // corresponding entry in api-schema.json will cause these tests to fail,
    // prompting the developer to add a type test (and add to TESTED_SCHEMAS)
    // or explicitly mark it as excluded.

    describe('coverage', () => {
        it('all schemas are tested or explicitly excluded', () => {
            const allSchemas = Object.keys(apiSchema.components.schemas);
            const uncovered = allSchemas.filter(
                (s) => !TESTED_SCHEMAS.has(s) && !EXCLUDED_SCHEMAS.has(s),
            );

            expect(uncovered).toEqual([]);
        });

        it('TESTED_SCHEMAS contains only schemas that exist in api-schema.json', () => {
            const allSchemas = new Set(
                Object.keys(apiSchema.components.schemas),
            );
            const phantom = [...TESTED_SCHEMAS].filter(
                (s) => !allSchemas.has(s),
            );

            expect(phantom).toEqual([]);
        });

        it('EXCLUDED_SCHEMAS contains only schemas that exist in api-schema.json', () => {
            const allSchemas = new Set(
                Object.keys(apiSchema.components.schemas),
            );
            const phantom = [...EXCLUDED_SCHEMAS].filter(
                (s) => !allSchemas.has(s),
            );

            expect(phantom).toEqual([]);
        });

        it('all API paths are known', () => {
            const allPaths = Object.keys(apiSchema.paths);
            const unknown = allPaths.filter((p) => !KNOWN_PATHS.has(p));

            expect(unknown).toEqual([]);
        });

        it('KNOWN_PATHS contains only paths that exist in api-schema.json', () => {
            const allPaths = new Set(Object.keys(apiSchema.paths));
            const phantom = [...KNOWN_PATHS].filter((p) => !allPaths.has(p));

            expect(phantom).toEqual([]);
        });
    });
});
