import { describe, expect, it } from 'vitest';
import type { Habit, TrackData } from '@/types/track';
import type { LifeViewData, WeekViewData, YearViewData } from '@/types/view';
import apiSchema from '../api-schema.json';

type SchemaMap = typeof apiSchema.components.schemas;

/**
 * Returns sorted property names from an OpenAPI component schema.
 */
function schemaKeys(name: keyof SchemaMap): string[] {
    const schema = apiSchema.components.schemas[name] as {
        properties?: Record<string, unknown>;
    };

    return Object.keys(schema.properties ?? {}).sort();
}

/**
 * Builds a sorted list of keys from a TypeScript type.
 *
 * The mapped type `{ [K in keyof Required<T>]: true }` ensures every
 * property of T must be listed — a compile error fires if one is
 * missing.  Comparing this list against the OpenAPI schema catches
 * additions / removals on either side.
 */
function typeKeys<T>(obj: { [K in keyof Required<T>]: true }): string[] {
    return Object.keys(obj).sort();
}

// ─── API Contract Tests ─────────────────────────────────────────
//
// These tests verify that the frontend TypeScript types stay in sync
// with the backend API schema generated by Scramble.
//
// If a backend resource adds or removes a field, `api-schema.json`
// changes and the corresponding assertion below will fail, forcing
// the developer to update the TypeScript type (or revert the backend
// change).

describe('API contract', () => {
    it('TrackResource schema matches TrackData type', () => {
        const schema = schemaKeys('TrackResource');
        const ts = typeKeys<Omit<TrackData, 'habits' | 'activityData'>>({
            date: true,
            dayName: true,
            dateFormatted: true,
            isToday: true,
            totalHabits: true,
            completedCount: true,
            dailyNoteContent: true,
            translations: true,
        });

        expect(schema).toEqual(ts);
    });

    it('WeekViewResource schema matches WeekViewData type', () => {
        const schema = schemaKeys('WeekViewResource');
        const ts = typeKeys<WeekViewData>({
            start: true,
            end: true,
            startFormatted: true,
            endFormatted: true,
            endFormattedFull: true,
            year: true,
            isCurrent: true,
        });

        expect(schema).toEqual(ts);
    });

    it('YearViewResource schema matches YearViewData type', () => {
        const schema = schemaKeys('YearViewResource');
        const ts = typeKeys<YearViewData>({
            selected: true,
            birthdate: true,
            currentAge: true,
        });

        expect(schema).toEqual(ts);
    });

    it('LifeViewResource schema matches LifeViewData type', () => {
        const schema = schemaKeys('LifeViewResource');
        const ts = typeKeys<LifeViewData>({
            birthdate: true,
            currentAge: true,
            weeksLived: true,
            yearsRemaining: true,
        });

        expect(schema).toEqual(ts);
    });

    it('HabitResource schema matches Habit type', () => {
        const schema = schemaKeys('HabitResource');
        const ts = typeKeys<Habit>({
            id: true,
            name: true,
            description: true,
            iterations_required: true,
            is_completed: true,
            current_iteration: true,
            sort_order: true,
        });

        expect(schema).toEqual(ts);
    });

    it('all expected endpoints exist', () => {
        const paths = Object.keys(apiSchema.paths);

        expect(paths).toContain('/track');
        expect(paths).toContain('/track/toggle');
        expect(paths).toContain('/track/daily-note');
        expect(paths).toContain('/view/week');
        expect(paths).toContain('/view/year');
        expect(paths).toContain('/view/life');
    });
});
